
// Types
export const COMPONENT_SET_TYPE = 'COMPONENT_SET'
export const PROPERTY_VARIANT_TYPE = 'VARIANT';

// Messages
export const MESSAGE_COMPONENT_NOT_SELECTED = 'MESSAGE_COMPONENT_NOT_SELECTED';
export const MESSAGE_ERROR = 'MESSAGE_ERROR';
export const MESSAGE_COMPONENT_SELECTED = 'MESSAGE_COMPONENT_SELECTED';
export const MESSAGE_GET_VARIANTS = 'MESSAGE_GET_VARIANTS';
export const MESSAGE_GET_PROPERTIES = 'MESSAGE_GET_PROPERTIES';
export const MESSAGE_GET_DIRECTIONS = 'MESSAGE_GET_DIRECTIONS';
export const MESSAGE_GET_GAPS = 'MESSAGE_GET_GAPS';
export const MESSAGE_GET_PROPERTIES_WITH_VALUES = 'MESSAGE_GET_PROPERTIES_WITH_VALUES';
export const MESSAGE_CHANGE_PROPERTIES = 'MESSAGE_CHANGE_PROPERTIES';

// Numbers
export const DEFAULT_GAP = 40;

// Gaps
export const ROWS_GAP_FIELD = 'ROWS_GAP_FIELD';
export const COLUMNS_GAP_FIELD = 'COLUMNS_GAP_FIELD';
